// Empty requests
DELETE http://localhost:23456/auth/removeUser
###
POST http://localhost:23456/auth/createUser
###
POST http://localhost:23456/auth/login
###
GET http://localhost:23456/auth/auth
###

POST http://localhost:23456/auth/createUser
Content-Type: application/json

{
    "username": "dula",
    "password": "12345678"
}

###

DELETE http://localhost:23456/auth/removeUser
Content-Type: application/json

{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlMGM1YjQ4Ni1jZTIzLTQzYjktYjdjMi0zOWJkYWY3MDdjY2QiLCJ1c2VybmFtZSI6ImR1bGEiLCJpYXQiOjE2NTQ0MjkzOTB9.j9qo8dp0wyAx_0Rb1jPZoTLBQwZ1PmCXkDJj3KvD89k"
}

###

POST http://localhost:23456/auth/login
Content-Type: application/json

{
    "username": "dula",
    "password": "12345678"
}

###

GET http://localhost:23456/auth/auth
Content-Type: application/json

{
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIwMzhhY2FkNi0wYjk1LTQ3MDctOWI0Mi0yZDUzZDU2ZDRiZGUiLCJ1c2VybmFtZSI6ImR1bGEiLCJpYXQiOjE2NTQ0MjkyMjJ9.BXjNhDQ8XhALb7vsUtLL-orGArWfFKATbSfh3BgmBdk"
}

###