// Empty requests
DELETE http://localhost:3000/removeUser
###
POST http://localhost:3000/createUser
###
POST http://localhost:3000/login
###
GET http://localhost:3000/auth
###

POST http://localhost:3000/createUser
Content-Type: application/json

{
    "username": "dula",
    "password": "12345678"
}

###

DELETE http://localhost:3000/removeUser
Content-Type: application/json

{
    "jwt": "INSERT JWT from createUser || login response"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "dula",
    "password": "12345678"
}

###

GET http://localhost:3000/auth
Content-Type: application/json

{
    "jwt": "INSERT JWT from createUser || login response"
}

###